name: Elparadisogonzalo Dapp CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build dApp (optional)
      run: npm run build

    - name: Deploy to IPFS (via Pinata or Web3.Storage)
      run: |
        npx ipfs add -r build/
        echo "Deploy manually using your preferred IPFS node if needed"
