mkdir -p .github/workflows
echo 'name: Deploy dApp

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build
' > .github/workflows/deploy.yml

git add .github/workflows/deploy.yml
git commit -m "Fix deploy.yml"
git push
