github.com:
    users:
        koagonzalo11:
            oauth_token: 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
    git_protocol: ssh
    user: koagonzalo11
    oauth_token: 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
