github.com:
    users:
        koagonzalo11:
            oauth_token: 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
    git_protocol: ssh
    user: koagonzalo11
    oauth_token: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
