name: Deploy Frontend to IPFS and Update Domain

on:
  push:
    paths:
      - 'packages/frontend/**'
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build Frontend
        run: yarn workspace frontend build

      - name: Install IPFS CLI
        run: |
          curl -O https://dist.ipfs.tech/kubo/v0.27.0/kubo_v0.27.0_linux-amd64.tar.gz
          tar -xvzf kubo_v0.27.0_linux-amd64.tar.gz
          sudo install kubo/ipfs /usr/local/bin/ipfs

      - name: Init IPFS Node & Add Files
        run: |
          ipfs init
          ipfs daemon &
          sleep 5
          CID=$(ipfs add -r packages/frontend/dist | tail -n 1 | awk '{ print $2 }')
          echo "CID=$CID" >> $GITHUB_ENV

      - name: Update Unstoppable Domain DNSLink
        run: |
          curl -X PATCH "https://api.unstoppabledomains.com/v1/domains/elparadisogonzalo.com/records" \
            -H "Authorization: Bearer ${{ secrets.UD_API_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{
              "records": {
                "dns.ipfs.hash": "${{ env.CID }}"
              }
            }'

