name: dApp CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  slither-check:
    runs-on: ubuntu-latest
    container:
      image: slither-local   # your Docker image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Slither security analysis
        run: |
          docker run --rm -v "${GITHUB_WORKSPACE}":/project -w /project slither-local /project/Assets3-1e473f24/contracts --solc /usr/local/bin/solc

  frontend-build-deploy:
    runs-on: ubuntu-latest
    needs: slither-check
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Install IPFS CLI
        run: |
          wget https://dist.ipfs.io/go-ipfs/v0.24.0/go-ipfs_v0.24.0_linux-amd64.tar.gz
          tar -xvzf go-ipfs_v0.24.0_linux-amd64.tar.gz
          sudo bash go-ipfs/install.sh

      - name: Deploy to IPFS
        run: ipfs add -r ./dist | tail -n1 | awk '{print $2}' > cid.txt

      - name: Update Unstoppable Domain DNSLink
        env:
          UD_API_KEY: ${{ secrets.UD_API_KEY }}
        run: |
          CID=$(cat cid.txt)
          curl -X POST "https://api.unstoppabledomains.com/dns/update" \
            -H "Authorization: Bearer $UD_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"domain\": \"elparadisogonzalo.com\", \"dnslink\": \"$CID\"}"
