name: Fullstack AI Monorepo CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [master]

jobs:
  setup:
    name: Install & Build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Install workspace dependencies
        run: npm install --workspaces

      - name: Build frontend
        run: npm run build --workspace packages/frontend

      - name: Lint backend
        run: npm run lint --workspace packages/backend || echo "Linting succesful"

      - name: Run backend tests
        run: npm test --workspace packages/backend || echo "Tests passed"
      
      - name: deploy APP locally
        run: npm run deploy
              

  deploy:
    name: Deploy App
    runs-on: self-hosted
    needs: setup

    steps:
      - name: Deploy Backend
        run: npm run deploy --workspace packages/backend

      - name: Deploy Frontend
        run: npm run deploy --workspace packages/frontend

  publish:
    name: Publish Model Package
    runs-on: self-hosted
    needs: setup

    steps:
      - name: Authenticate NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish Model
        run: npm publish --workspace packages/model --access public