name: Full CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-analyze-deploy:
    runs-on: ubuntu-latest

    env:
      PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
      PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
      UD_API_KEY: ${{ secrets.UD_API_KEY }}
      UD_API_SECRET: ${{ secrets.UD_API_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # -----------------------------
      # 1. Install Node + deps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      # -----------------------------
      # 2. Install Python + Slither
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Slither
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer

      # -----------------------------
      # 3. Compile & Analyze Contracts
      - name: Compile Contracts
        run: |
          solc --version
          slither ./contracts --solc solc

      # -----------------------------
      # 4. Run Smart Contract Tests
      - name: Run Hardhat Tests
        run: |
          npx hardhat test

      # -----------------------------
      # 5. Build Frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # -----------------------------
      # 6. Upload to IPFS via Pinata
      - name: Deploy Frontend to IPFS
        run: |
          cd frontend
          node scripts/ipfs-upload.js

      # -----------------------------
      # 7. Update Unstoppable Domain
      - name: Update UD DNSLink
        run: |
          cd frontend
          node scripts/update-ud-dnslink.js

