name: 📓 Log IPFS CID Deployments

on:
  workflow_run:
    workflows: ["🚀 Deploy to IPFS & Update UD Domain"]
    types:
      - completed

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Load previous log
      id: getlog
      run: |
        [ -f deploy-log.json ] || echo "[]" > deploy-log.json
        echo "log=$(cat deploy-log.json)" >> $GITHUB_OUTPUT

    - name: Append latest CID
      run: |
        CID=$(curl -s https://api.pinata.cloud/data/pinList?status=pinned \
          -H "pinata_api_key: ${{ secrets.PINATA_API_KEY }}" \
          -H "pinata_secret_api_key: ${{ secrets.PINATA_SECRET_API_KEY }}" | jq -r '.rows[0].ipfs_pin_hash')

        ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        commit=$(git rev-parse --short HEAD)

        new_entry="{\"timestamp\":\"$ts\",\"cid\":\"$CID\",\"commit\":\"$commit\"}"
        echo $(jq ". + [$new_entry]" deploy-log.json) > deploy-log.json

    - name: Commit the updated log
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git add deploy-log.json
        git commit -m "📓 Update deploy-log.json with new CID"
        git push origin main
