name: Slither Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  slither:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer

      - name: Run Slither
        run: |
          slither contracts/ --solc /usr/local/bin/solc
