name: Verify GPG Commit Signature

on:
  push:
    branches:
      - main
      - master

jobs:
  verify-signature:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Verify latest 5 GPG signatures
        run: |
          git log --show-signature -n 5
          SIGNED_COUNT=$(git log --show-signature -n 5 | grep -c "Good signature")
          if [ "$SIGNED_COUNT" -lt 5 ]; then
            echo "❌ Not all commits are GPG signed!"
            exit 1
          else
            echo "✅ All recent commits are properly signed."
          fi
